# MiniKOTH Configuration File
# Configure all aspects of the KOTH system here

settings:
  capture-time: 300 # Time in seconds to capture
  message-interval: 30 # Interval for remaining time messages
  prefix: "&8[&bMiniKOTH&8]"
  chest-despawn-time: 300 # Time in seconds before chest despawns after capture

messages:
  start-capture: "&aYou started capturing the KOTH!"
  leave-capture: "&cYou left the KOTH area!"
  cannot-open: "&cOnly the KOTH winner can open this chest!"
  time-remaining: "&eTime remaining: {time}"
  koth-captured: "&a{player} has captured the KOTH!"
  koth-started: "&bThe KOTH {name} has started!"
  koth-ended: "&bThe KOTH {name} has ended!"
  chest-spawned: "&aA reward chest has spawned at the KOTH!"
  help-header: "&8=== &bMiniKOTH Help &8==="
  help-format: "&b/{command} &7- {description}"
  help-footer: "&8=========================="
  no-permission: "&cYou don't have permission to use this command!"
  command-error: "&cAn error occurred while executing the command."
  player-only: "&cThis command can only be used by players!"
  create-usage: "&cUsage: /minikoth create <name>"
  koth-exists: "&cA KOTH with that name already exists!"
  no-selection: "&cYou must make a WorldEdit selection first!"
  koth-created: "&aKOTH {name} has been created successfully!"
  set-chest-reminder: "&eRemember to set the chest spawn location with /minikoth setspawn {name}"
  creation-failed: "&cFailed to create KOTH. Please try again."
  delete-usage: "&cUsage: /minikoth delete <name>"
  koth-not-found: "&cKOTH with that name does not exist!"
  cannot-delete-active: "&cCannot delete an active KOTH! Stop it first."
  koth-deleted: "&aKOTH {name} has been deleted successfully!"
  setspawn-usage: "&cUsage: /minikoth setspawn <name>"
  cannot-modify-active: "&cCannot modify an active KOTH!"
  chest-spawn-set: "&aChest spawn location for KOTH {name} has been set!"
  reward-usage: "&cUsage: /minikoth reward <add|remove|list>"
  reward-add-usage: "&cUsage: /minikoth reward add <command>"
  reward-remove-usage: "&cUsage: /minikoth reward remove <command>"
  reward-added: "&aReward command '{command}' has been added!"
  reward-removed: "&aReward command '{command}' has been removed!"
  reward-exists: "&cThat reward command already exists!"
  reward-not-found: "&cThat reward command was not found!"
  no-rewards: "&cThere are no reward commands configured!"
  reward-list-header: "&8=== &bKOTH Rewards &8==="
  reward-list-format: "&b{number}. &7{command}"
  reward-list-footer: "&8========================="
  schedule-usage: "&cUsage: /minikoth schedule <add|remove|list|enable|disable>"
  schedule-add-usage: "&cUsage: /minikoth schedule add <HH:mm>"
  schedule-remove-usage: "&cUsage: /minikoth schedule remove <HH:mm>"
  schedule-added: "&aSchedule time {time} has been added!"
  schedule-removed: "&aSchedule time {time} has been removed!"
  schedule-invalid-time: "&cInvalid time format! Use HH:mm (24-hour format)"
  schedule-not-found: "&cThat schedule time was not found!"
  no-schedules: "&cThere are no scheduled times configured!"
  schedule-list-header: "&8=== &bKOTH Schedules &8==="
  schedule-list-format: "&b{number}. &7{time}"
  schedule-list-footer: "&8========================="
  schedule-status: "&7Current status: &b{status}"
  schedule-enabled: "&aSchedules have been enabled!"
  schedule-disabled: "&cSchedules have been disabled!"
  start-usage: "&cUsage: /minikoth start <name>"
  stop-usage: "&cUsage: /minikoth stop <name>"
  koth-already-active: "&cThis KOTH is already active!"
  koth-not-active: "&cThis KOTH is not currently active!"
  koth-started-manual: "&aKOTH {name} has been manually started!"
  koth-stopped-manual: "&aKOTH {name} has been manually stopped!"
  start-failed: "&cFailed to start KOTH. Please try again."

rewards:
  commands:
    - "give {player} diamond 64"
    - "eco give {player} 1000"

schedules:
  enabled: true
  timezone: "America/Argentina/Buenos_Aires"
  times:
    - "14:00"
    - "20:00"
    - "22:00"

koths: {}  # This section will store KOTH data